### POST Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "usenname": "w",
    "password": "w"
}



### Get a Students
GET http://localhost:3000/student/:id
Content-Type: application/json

{
    "name": "Max Kim"
}
